### ISSUE TITLE
Output contains previous generations

### ISSUE THREAD

**Issue by pdstefan** [mkimuram/k8sviz#32]
Hi.

I am trying to generate the deployment diagram from a namespace but the output for deployments contains all previous RS . 
Output for one of deployment (extremely zoomed in): 
![image](https://user-images.githubusercontent.com/3641148/123092141-d613b080-d432-11eb-9f0f-55ebb921933d.png)

The NS has multiple microservices (10+) and when 10+ generations are tracked in the output file, you can imagine the file contains many objects and only zooming in you can (somehow) see the individual objects (PNG output is worst, as icons and text are very small) 
![image](https://user-images.githubusercontent.com/3641148/123092329-0d825d00-d433-11eb-9e5f-3a75b092ea1d.png)

 kube 17 and 18, same behavior. 

Great tool! Thank you for the effort!

**Comment by mkimuram** [comment]
@pdstefan

Thank you for reporting the issue.

PR #33 should fix this issue and I've pushed the test image as `mkimuram/k8sviz:devel`.
Could you test with `-i mkimuram/k8sviz:devel` option added to check if it works as expected?
(Any feedback is welcome, like adding option to toggle whether to show old ones).

Note that I tested with the below deployment and confirmed that old Replicaset is not shown.

```
kubectl create deploy --image=nginx nginx
kubectl scale --replicas=3 deploy/nginx
kubectl set image deploy/nginx nginx=nginx:stable
```

**Comment by mkimuram** [comment]
Above PR is merged and the image is updated. Feel free to open this issue, if it needs any improvements. Thank you for your reporting issue.

**Comment by pdstefan** [comment]
Just tried the `devel`  image and I  still see the previous replicasets. For clarification: we are deploying using kustomize and the replicasets are the observed "previous generations" of the same deployments (usually only minor changes to deployments like image and limits). 

Result of: `sudo ./k8sviz.sh -n xyq -t png -o dia.png -i mkimuram/k8sviz:devel`

![dia](https://user-images.githubusercontent.com/3641148/125156862-67439080-e170-11eb-9e87-1a044e1cd257.png)

Thank you.

**Comment by mkimuram** [comment]
@pdstefan 

Thank you for your comments.

How is the `DESIRED ` and `CURRENT` shown for your "previous generations" of replicasets for the same deployment?

In my environment, for the below commands:
```
kubectl create deploy --image=nginx nginx
kubectl scale --replicas=3 deploy/nginx
kubectl set image deploy/nginx nginx=nginx:stable
```

`DESIRED ` and `CURRENT` for the old replicaset are 0. 
```
kubectl get all
NAME                         READY   STATUS    RESTARTS   AGE
pod/nginx-7cd7b48495-8kptb   1/1     Running   0          9s
pod/nginx-7cd7b48495-cjjn6   1/1     Running   0          7s
pod/nginx-7cd7b48495-hjhg6   1/1     Running   0          11s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   12d

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx   3/3     3            3           36s

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-6799fc88d8   0         0         0       36s
replicaset.apps/nginx-7cd7b48495   3         3         3       11s
```

And the latest k8sviz exclude such replicaset and show the result for `./k8sviz.sh -t png -o nostalers.png`.
<img src="https://user-images.githubusercontent.com/36450643/125321321-9261e780-e30a-11eb-9e59-e222cd911a2d.png" width="400" />

**Comment by mkimuram** [comment]
Note that I've just updated the k8sviz.sh to ensure the latest image is used. So, to test the latest image, please re-install(re-download) k8sviz.sh.

**Comment by pdstefan** [comment]
Hi. Sorry for the late reply (work is hell lately). 

Try this : 
```
cat << EOK > nginx-deploy.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: viz-demo-deployment
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: viz-demo-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.10
        ports:
        - containerPort: 80
EOK 
kubectl create ns viz-demo-deployment
kubectl apply -f nginx-deploy.yaml
sed -i 's/nginx:1.17.10/nginx:1.19.2/' nginx-deploy.yaml
kubectl apply -f nginx-deploy.yaml 
sed -i 's/nginx:1.19.2/nginx:1.21.0/' nginx-deploy.yaml
kubectl apply -f nginx-deploy.yaml 
sudo ./k8sviz.sh -n viz-demo-deployment  -t png -o viz-demo-deployment.png -i mkimuram/k8sviz:devel #used the latest k8sviz.sh version 
```
![viz-demo-deployment](https://user-images.githubusercontent.com/3641148/126174939-3c361cd7-0142-45e5-b8e0-7ed2d5cd36eb.png)

You can see that the previous generations of the ReplicaSets show up (in the previous image I posted up to 10 generations are tracked) .  Am I doing something wrong? 

As always: thank you for your time!

**Comment by mkimuram** [comment]
@pdstefan

Thank you for your feedback. Could you try without `-i mkimuram/k8sviz:devel` option?
```
sudo ./k8sviz.sh -n viz-demo-deployment  -t png -o viz-demo-deployment.png
```

I noticed that I accidentally overwrite the mkimuram/k8sviz:devel image without this feature (and worked as you pointed out). Without the option, it should use 0.3.1 image and work fine.


> As always: thank you for your time!

Thank you too for your time!
